org 7c00h ; ORIGIN ADDRESS
MOV AH,0Eh ; 0E TELETYPE MODE
MOV AL,1 ; CHARACTER TO WRITE, ASCII CHARACTER 1 IS THE HAPPY FACE
INT 10h ; CALL THE INTERRUPT FOR VIDEO SERVICES

TIMES 510-($-$$) DB 0 ; PAD UNTIL 510TH BYTE
DW 55AAh ; BOOT SIGNATURE
;TIMES 1474560-($-$$) DB 0
