;
; This is a very cumbersome way of printing a string
;
org 7c00h ; ORIGIN ADDRESS


MOV AH,0Eh ; 0E TELETYPE MODE
MOV AL,[STRING] ; CHARACTER TO WRITE, ASCII CHARACTER H
INT 10h ; CALL THE INTERRUPT FOR VIDEO SERVICES

MOV AH,0Eh ; 0E TELETYPE MODE
MOV AL,[STRING+1] ; CHARACTER TO WRITE, ASCII CHARACTER E
INT 10h ; CALL THE INTERRUPT FOR VIDEO SERVICES

MOV AH,0Eh ; 0E TELETYPE MODE
MOV AL,[STRING+2] ; CHARACTER TO WRITE, ASCII CHARACTER L
INT 10h ; CALL THE INTERRUPT FOR VIDEO SERVICES

MOV AH,0Eh ; 0E TELETYPE MODE
MOV AL,[STRING+3] ; CHARACTER TO WRITE, ASCII CHARACTER L
INT 10h ; CALL THE INTERRUPT FOR VIDEO SERVICES

MOV AH,0Eh ; 0E TELETYPE MODE
MOV AL,[STRING+4] ; CHARACTER TO WRITE, ASCII CHARACTER O
INT 10h ; CALL THE INTERRUPT FOR VIDEO SERVICES

MOV AH,0Eh ; 0E TELETYPE MODE
MOV AL,[STRING+5] ; CHARACTER TO WRITE, ASCII CHARACTER ' '
INT 10h ; CALL THE INTERRUPT FOR VIDEO SERVICES

MOV AH,0Eh ; 0E TELETYPE MODE
MOV AL,[STRING+6] ; CHARACTER TO WRITE, ASCII CHARACTER W
INT 10h ; CALL THE INTERRUPT FOR VIDEO SERVICES

MOV AH,0Eh ; 0E TELETYPE MODE
MOV AL,[STRING+7] ; CHARACTER TO WRITE, ASCII CHARACTER O
INT 10h ; CALL THE INTERRUPT FOR VIDEO SERVICES

MOV AH,0Eh ; 0E TELETYPE MODE
MOV AL,[STRING+8] ; CHARACTER TO WRITE, ASCII CHARACTER R
INT 10h ; CALL THE INTERRUPT FOR VIDEO SERVICES

MOV AH,0Eh ; 0E TELETYPE MODE
MOV AL,[STRING+9] ; CHARACTER TO WRITE, ASCII CHARACTER L
INT 10h ; CALL THE INTERRUPT FOR VIDEO SERVICES

MOV AH,0Eh ; 0E TELETYPE MODE
MOV AL,[STRING+10] ; CHARACTER TO WRITE, ASCII CHARACTER D
INT 10h ; CALL THE INTERRUPT FOR VIDEO SERVICES

MOV AH,0Eh ; 0E TELETYPE MODE
MOV AL,[STRING+11] ; CHARACTER TO WRITE, ASCII CHARACTER !
INT 10h ; CALL THE INTERRUPT FOR VIDEO SERVICES

STRING DB "HELLO WORLD!",0
TIMES 510-($-$$) DB 0 ; PAD UNTIL 510TH BYTE
DW 05AAh ; BOOT SIGNATURE
;TIMES 1474560-($-$$) DB 0