;
; An example of a simple print routine
;
org 7c00h ; ORIGIN ADDRESS

LEA DI,[MSG1] ; LOAD THE MSG1 ADDRESS INTO DI
CALL print ; CALL THE PRINT ROUTINE
LEA DI,[MSG2] ; LOAD THE MSG2 ADDRESS INTO DI
CALL print ; CALL THE PRINT ROUTINE

fin: ; INFINITE LOOP
JMP fin

print: ; START OF THE PRINT ROUTINE
PUSH AX ; SAVE AX
print_loop:
	MOV AL, [DI] ; MOVE THE CONTENTS OF DI INTO AL
	CMP AL, 0 ; WE ARE LOOKING FOR THE STRING TERMINATOR 0
	JZ print_finished ; IF TRUE WE FOUND THE STRING TERMINATOR AND CAN EXIT THIS ROUTINE
	
	MOV AH,0Eh ; 0E TELETYPE MODE
	INT 10h ; CALL THE INTERRUPT FOR VIDEO SERVICES
	INC DI ; ADVANCE THE POINTER
	JMP print_loop ; CONTINUE ITERATING OVER OUR STRING UNTIL WE FIND HOPEFULLY FIND THE NUL TERMINATOR
print_finished :
POP AX ; RESTORE AX
RET ; RETURN TO CALLER

MSG1 DB "HELLO WORLD!",10,13,0 ; 10,13 LF AND CR ,0 TERMINATES THE STRING
MSG2 DB "GOODBYE WORLD!",10,13,0 ; 10,13 LF AND CR, 0 TERMINATES THE STRING

TIMES 510-($-$$) DB 0 ; PAD UNTIL 510TH BYTE
DW 05AAh ; BOOT SIGNATURE
;TIMES 1474560-($-$$) DB 0